## 标量
标量由只有一个元素的张量表示。 下面的代码将实例化两个标量，并执行一些熟悉的算术运算，即加法、乘法、除法和指数。

In [32]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

##  向量
向量可以被视为标量值组成的列表。 这些标量值被称为向量的元素（element）或分量（component）。 

In [33]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [34]:
x[3]

tensor(3)

### 长度、维度和形状
向量只是一个数字数组，就像每个数组都有一个长度一样，每个向量也是如此。

In [35]:
# len()函数来访问张量的长度。
len(x)

4

In [36]:
# 通过.shape属性访问向量的长度。
x.shape

torch.Size([4])

## 矩阵
正如向量将标量从零阶推广到一阶，矩阵将向量从一阶推广到二阶。

In [37]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [38]:
# 矩阵的转置。
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [39]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [40]:
B == B.T 

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量
就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。 张量（本小节中的“张量”指代数对象）是描述具有任意数量轴的
维数组的通用方法。 例如，向量是一阶张量，矩阵是二阶张量。 

当我们开始处理图像时，张量将变得更加重要，图像以
维数组形式出现， 其中3个轴对应于高度、宽度，以及一个通道（channel）轴， 用于表示颜色通道（红色、绿色和蓝色）。

In [41]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的基本性质
标量、向量、矩阵和任意数量轴的张量（本小节中的“张量”指代数对象）有一些实用的属性。 例如，从按元素操作的定义中可以注意到，任何按元素的一元运算都不会改变其操作数的形状。 同样，给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量。 例如，将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法。

In [42]:
import numpy as np

A = np.arange(20).reshape(5, 4)
B = A.copy()
A, A + B

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]]))

具体而言，两个矩阵的按元素乘法称为Hadamard积（Hadamard product）

![](./img/Snipaste_2024-04-14_16-38-05.JPG)

In [43]:
A * B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [44]:
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
X = np.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]]),
 (2, 3, 4))

## 降维


In [45]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [46]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
A.shape, A.sum()

((5, 4), 190)

In [48]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape # shape与列数相同

(array([40, 45, 50, 55]), (4,))

In [49]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1

array([ 6, 22, 38, 54, 70])

In [50]:
A.sum(axis=(0, 1))

190

In [51]:
A.mean()

9.5

In [52]:
# A.numel()函数有点问题


### 非降维求和

In [53]:
sum_A = A.sum(axis=1, keepdims = True)
sum_A

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [54]:
A / sum_A

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])

In [55]:
A.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]], dtype=int32)

## 点积

In [58]:
import torch

u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)