In [22]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [24]:
x.requires_grad_(True)
x.grad

In [25]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [26]:
# 通过调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [7]:
x.grad.zero_() # 对梯度清零

tensor([0., 0., 0., 0.])

In [8]:
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [9]:
y.backward()

In [10]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [11]:
x.grad

tensor([1., 1., 1., 1.])

In [12]:
y = x.sum()
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [13]:
y

tensor(6., grad_fn=<SumBackward0>)

In [14]:
y = x.sum()

In [15]:
y

tensor(6., grad_fn=<SumBackward0>)

In [16]:
y.backward()

In [17]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [18]:
x.grad

tensor([3., 3., 3., 3.])