NumPy（Numerical Python的简称）是Python数值计算最重要的基础包。

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [4]:
my_list = list(range(1000000))
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [5]:
%time for _ in range(100): my_arr2 = my_arr * 2

CPU times: total: 125 ms
Wall time: 123 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 625 ms
Wall time: 618 ms


## 4.1 NumPy的ndarray：一种多维数组对象

In [7]:
import numpy as np

In [8]:
data = np.random.randn(2,3)
data

array([[ 0.6015999 ,  1.57727734,  0.45158399],
       [-0.04278789, -0.78879611,  0.56302498]])

In [9]:
data * 10

array([[ 6.01599905, 15.77277336,  4.51583993],
       [-0.42787887, -7.8879611 ,  5.63024976]])

In [10]:
data + data

array([[ 1.20319981,  3.15455467,  0.90316799],
       [-0.08557577, -1.57759222,  1.12604995]])

In [11]:
data.shape

(2, 3)

### 创建ndarray

In [12]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.zeros([1,2])

array([[0., 0.]])

In [21]:
np.zeros((1,2))

array([[0., 0.]])

np.zeros((1,2)) 和 np.zeros([1,2])是一样的效果

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray的数据类型

In [23]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [24]:
arr2 = np.array([1,2,3], dtype='int32')
arr2

array([1, 2, 3])

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int32')

In [27]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [28]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [29]:
arr = np.array([3.7, -1.2, 0.5, 10.1, 11.6])
arr

array([ 3.7, -1.2,  0.5, 10.1, 11.6])

In [30]:
arr.astype(np.int32)
arr

array([ 3.7, -1.2,  0.5, 10.1, 11.6])

In [31]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [32]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [33]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [34]:
# 说明，规范的写法应该是 astype(np.float64)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
numeric_strings.dtype

dtype('S4')

### NumPy数组的运算


In [36]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [38]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
## 开根号
arr ** 0.5


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [41]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [42]:
arr2 > arr2

array([[False, False, False],
       [False, False, False]])

### 基本的索引和切片

In [43]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[0],arr[5]

(0, 5)

In [45]:
arr[5:8]

array([5, 6, 7])

In [46]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [47]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [48]:
arr_slice[1] 

12

In [49]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
# 当我修改arr_slice中的值，变动也会体现在原始数组arr中：
arr_slice[1] = 12345

In [51]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [52]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[2]

array([7, 8, 9])

In [55]:
# 以下两种方式等价
arr2d[0][2]
arr2d[0, 2]

3

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d.shape

(2, 2, 3)

In [58]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
old_values = arr3d[0].copy()

In [60]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
old_values[0], old_values

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [63]:
arr3d[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [64]:
# 其实是将 old_values 赋值给 arr3d[0]
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[1,0] 

array([7, 8, 9])

In [67]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [68]:
x[0]

array([7, 8, 9])

### 切片索引

In [69]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [70]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [71]:
arr2d[:2] # 获取前两行

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr2d[:2, 1:] # 获取前两行，然后截取第2列之后的元素（1,2列）

array([[2, 3],
       [5, 6]])

In [73]:
arr2d[1, :2]

array([4, 5])

In [74]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[:2, 2]

array([3, 6])

### 布尔型索引

In [76]:
# 来看这样一个例子，假设我们有一个用于存储数据的数组以及一个存储姓名的数组（含有重复项）
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [77]:
data = np.random.randn(7,4)
data

array([[-1.95657684, -0.79720649, -0.57385925,  0.68325189],
       [ 1.22623312, -1.81644562, -0.98208312, -0.5006181 ],
       [ 0.41294216,  0.85984273,  0.7141093 , -0.67510907],
       [ 0.72709116,  0.10144781,  1.34811839, -0.14890689],
       [-0.00313005,  0.61006027,  0.27605543, -0.66010417],
       [-1.24330058, -0.47399645, -1.03718759,  0.2001416 ],
       [-0.18370494, -0.03839695, -0.87970768, -1.15626041]])

In [78]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [79]:
data[names == 'Bob']

array([[-1.95657684, -0.79720649, -0.57385925,  0.68325189],
       [ 0.72709116,  0.10144781,  1.34811839, -0.14890689]])

In [80]:
# 我选取了names == 'Bob'的行，并索引了列：
data[names=='Bob', 2:]

array([[-0.57385925,  0.68325189],
       [ 1.34811839, -0.14890689]])

In [81]:
data[names=='Bob', 3]

array([ 0.68325189, -0.14890689])

In [82]:
# data[names=='Bob', 4]
# 会报错

In [83]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [84]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [85]:
data[~(names == 'Bob')] # names != Bob, [1,2,4,5,6], 此表达式取的是1,2,4,5,6行

array([[ 1.22623312, -1.81644562, -0.98208312, -0.5006181 ],
       [ 0.41294216,  0.85984273,  0.7141093 , -0.67510907],
       [-0.00313005,  0.61006027,  0.27605543, -0.66010417],
       [-1.24330058, -0.47399645, -1.03718759,  0.2001416 ],
       [-0.18370494, -0.03839695, -0.87970768, -1.15626041]])

In [86]:
data

array([[-1.95657684, -0.79720649, -0.57385925,  0.68325189],
       [ 1.22623312, -1.81644562, -0.98208312, -0.5006181 ],
       [ 0.41294216,  0.85984273,  0.7141093 , -0.67510907],
       [ 0.72709116,  0.10144781,  1.34811839, -0.14890689],
       [-0.00313005,  0.61006027,  0.27605543, -0.66010417],
       [-1.24330058, -0.47399645, -1.03718759,  0.2001416 ],
       [-0.18370494, -0.03839695, -0.87970768, -1.15626041]])

In [87]:
cond = names == 'Bob'
data[~cond]

array([[ 1.22623312, -1.81644562, -0.98208312, -0.5006181 ],
       [ 0.41294216,  0.85984273,  0.7141093 , -0.67510907],
       [-0.00313005,  0.61006027,  0.27605543, -0.66010417],
       [-1.24330058, -0.47399645, -1.03718759,  0.2001416 ],
       [-0.18370494, -0.03839695, -0.87970768, -1.15626041]])

In [88]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [89]:
# 选取这三个名字中的两个需要组合应用多个布尔条件，使用&（和）、|（或）之类的布尔算术运算符即可：
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [90]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.        , 0.68325189],
       [1.22623312, 0.        , 0.        , 0.        ],
       [0.41294216, 0.85984273, 0.7141093 , 0.        ],
       [0.72709116, 0.10144781, 1.34811839, 0.        ],
       [0.        , 0.61006027, 0.27605543, 0.        ],
       [0.        , 0.        , 0.        , 0.2001416 ],
       [0.        , 0.        , 0.        , 0.        ]])

In [91]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.22623312, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.2001416 ],
       [0.        , 0.        , 0.        , 0.        ]])

### 花式索引
花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。假设我们有一个8×4数组：

In [92]:
arr = np.empty((8,4))

In [93]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [94]:
# 为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可：
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [95]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [96]:
# 一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：
arr = np.arange(32).reshape((8, 4))

In [97]:
arr[[1,5,7,2], [0,3,1,2]] # 第1、5、7、2行（从0开始算起）的0、3、1、2号元素

array([ 4, 23, 29, 10])

### 数组转置和轴对换
转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [99]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
arr.T # 转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [101]:
arr = np.random.randn(6,3)

In [102]:
np.dot(arr.T, arr)

array([[ 3.54783602,  1.91764785, -4.30347682],
       [ 1.91764785,  3.63214866, -3.32988607],
       [-4.30347682, -3.32988607,  8.53767837]])

## 4.2 通用函数：快速的元素级数组函数
通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。你可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器。

In [103]:
arr = np.arange(10)

In [104]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

这些都是一元（unary）ufunc。另外一些（如add或maximum）接受2个数组（因此也叫二元（binary）ufunc），并返回一个结果数组：

In [108]:
x = np.random.randn(8)

In [109]:
y = np.random.randn(8)

In [110]:
x

array([-0.84603636, -0.53520957,  1.28749152,  1.8744516 , -0.2553323 ,
       -0.73867373, -1.49103454, -0.67181187])

In [111]:
y

array([-0.55494081, -0.89986066,  1.30371708,  1.28238523, -1.0654393 ,
       -1.28556696,  0.03296914, -0.13620517])

In [112]:
np.maximum(x, y)

array([-0.55494081, -0.53520957,  1.30371708,  1.8744516 , -0.2553323 ,
       -0.73867373,  0.03296914, -0.13620517])

In [114]:
# np.maximum(x) # 会报错，传入一元会报错

## 4.3 利用数组进行数据处理
NumPy数组使你可以将许多种数据处理任务表述为简洁的数组表达式（否则需要编写循环）。用数组表达式代替循环的做法，通常被称为**矢量化**。一般来说，矢量化数组运算要比等价的纯Python方式快上一两个数量级（甚至更多），尤其是各种数值计算。在后面内容中（见附录A）我将介绍广播，这是一种针对矢量化计算的强大手段。

In [117]:
points = np.arange(-5, 5, 1)
points

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [118]:
xs, ys = np.meshgrid(points, points)
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [121]:
z = np.sqrt(xs**2 + ys ** 2)
z 

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

In [122]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

### 将条件逻辑表述为数组运算
numpy.where函数是三元表达式x if condition else y的矢量化版本。

In [124]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [126]:
# 假设我们想要根据cond中的值选取xarr和yarr的值：当cond中的值为True时，选取xarr的值，否则从yarr中选取。列表推导式的写法应该如下所示：
result = [ (x if c else y)
          for x, y, c in zip(xarr, yarr, cond)
]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [129]:
# 这有几个问题。第一，它对大数组的处理速度不是很快（因为所有工作都是由纯Python完成的）。第二，无法用于多维数组。若使用np.where，则可以将该功能写得非常简洁：
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [136]:
arr = np.random.rand(4,4)
arr

array([[0.6369102 , 0.17159097, 0.19725279, 0.10690161],
       [0.32339493, 0.84047403, 0.61134479, 0.10128488],
       [0.25121602, 0.85076803, 0.21945507, 0.87220307],
       [0.68992783, 0.62951008, 0.2534256 , 0.13328448]])

In [138]:
arr > 0.5

array([[ True, False, False, False],
       [False,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True, False, False]])

In [139]:
np.where(arr > 0.5, 2, -2)

array([[ 2, -2, -2, -2],
       [-2,  2,  2, -2],
       [-2,  2, -2,  2],
       [ 2,  2, -2, -2]])

In [140]:
np.where(arr > 0.5, 2, arr)

array([[2.        , 0.17159097, 0.19725279, 0.10690161],
       [0.32339493, 2.        , 2.        , 0.10128488],
       [0.25121602, 2.        , 0.21945507, 2.        ],
       [2.        , 2.        , 0.2534256 , 0.13328448]])

### 数学和统计方法
可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算。sum、mean以及标准差std等聚合计算（aggregation，通常叫做约简（reduction））既可以当做数组的实例方法调用，也可以当做顶级NumPy函数使用。

In [142]:
arr = np.random.rand(5,4)
arr

array([[0.78429754, 0.31068977, 0.56885945, 0.01394617],
       [0.37809588, 0.5520777 , 0.16501673, 0.8495752 ],
       [0.57757536, 0.12983989, 0.00916955, 0.89613721],
       [0.16765074, 0.75267486, 0.12692488, 0.81883979],
       [0.74664841, 0.01695956, 0.38601047, 0.66890893]])

In [143]:
arr.mean()

0.4459949053383377

In [144]:
np.mean(arr)

0.4459949053383377

In [145]:
arr.sum()

8.919898106766754

In [146]:
np.sum(arr)

8.919898106766754

In [147]:
# arr.mean(1)是“计算行的平均值”，arr.sum(0)是“计算每列的和”。
arr.mean(axis=1) # 计算每列的和

array([0.41944823, 0.48619138, 0.4031805 , 0.46652257, 0.45463184])

In [148]:
# 其他如cumsum和cumprod之类的方法则不聚合，而是产生一个由中间结果组成的数组：
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum() # 累加

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [149]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [150]:
arr.cumsum(axis=0) # 列累加

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [151]:
arr.cumprod(axis=1) # 行累乘

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

基本统计方法
- sum
- mean
- std、var 标准差、方差
- min、max 
- argmin、argmax 最大和最小元素的索引
- cumsum 所有元素的累计和
- cumprod 所有元素的累计积

### 用于布尔型数组的方法

In [153]:
arr = np.random.randn(100)

In [154]:
(arr > 0).sum()

53

In [155]:
(arr > 0)

array([ True,  True,  True, False,  True, False,  True, False, False,
       False, False, False,  True,  True, False, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True,
        True,  True, False,  True,  True, False, False, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True, False, False,  True, False, False,  True,
       False,  True,  True, False,  True, False, False, False, False,
        True, False,  True,  True,  True, False,  True, False, False,
        True])

另外还有两个方法any和all，它们对布尔型数组非常有用。any用于测试数组中是否存在一个或多个True，而all则检查数组中所有值是否都是True：

In [157]:
bools = np.array([False, False, True, False])

In [158]:
bools.any()

True

In [159]:
bools.all()

False

### 排序


In [160]:
arr = np.random.randn(6)
arr

array([ 1.43600597, -0.61422277, -0.81280399,  1.3727847 , -0.78875927,
        0.51472868])

In [162]:
arr.sort()
arr

array([-0.81280399, -0.78875927, -0.61422277,  0.51472868,  1.3727847 ,
        1.43600597])

多维数组可以在任何一个轴向上进行排序，只需将轴编号传给sort即可：

In [163]:
arr = np.random.randn(5, 3)
arr

array([[-0.62829019, -1.16144684, -0.39054427],
       [ 1.38655389,  0.6183468 , -0.01839081],
       [-0.68498924,  0.49428375, -1.95053089],
       [ 1.10407539, -0.23420404,  0.50005683],
       [ 0.67981765, -0.23319368,  0.63546652]])

In [165]:
arr.sort(1) # 1表示x轴，行
arr

array([[-1.16144684, -0.62829019, -0.39054427],
       [-0.01839081,  0.6183468 ,  1.38655389],
       [-1.95053089, -0.68498924,  0.49428375],
       [-0.23420404,  0.50005683,  1.10407539],
       [-0.23319368,  0.63546652,  0.67981765]])

In [166]:
arr.sort(0)  # 1表示y轴，列
arr

array([[-1.95053089, -0.68498924, -0.39054427],
       [-1.16144684, -0.62829019,  0.49428375],
       [-0.23420404,  0.50005683,  0.67981765],
       [-0.23319368,  0.6183468 ,  1.10407539],
       [-0.01839081,  0.63546652,  1.38655389]])

### 唯一化以及其它的集合逻辑
NumPy提供了一些针对一维ndarray的基本集合运算。最常用的可能要数np.unique了，它用于找出数组中的唯一值并返回已排序的结果：

In [167]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [168]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [171]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [172]:
np.unique(ints)

array([1, 2, 3, 4])